os: linux
dist: jammy
language: generic
addons:
  apt:
    packages:
      - libxml-xpath-perl
services:
  - docker

git:
  depth: false

env:
  global:
    - DOCKER_IMAGE_NAME=zendao-balancer
    - RELEASE_BRANCH=main

before_script: source ci/setup_env.sh

jobs:
  include:
    - name: "ZenDAO Balancer Docker Image Build"
      script: ci/docker.sh
      if: tag IS present

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  overwrite: true
  on:
    tags: true
    condition: $IS_A_RELEASE = true