os: linux
dist: jammy
language: generic
services:
  - docker

git:
  depth: false

env:
  global:
    - DOCKER_IMAGE_NAME=zencash/blockscout

before_script:
  - source ci/setup_env.sh

jobs:
  include:
    - name: build_and_publish
      script: ci/script.sh